print("|=" * 30)
print()
print("              _")
print("           __(Q.Q)<   Gobble! Gobble!")
print("           \\___)")
print("        ~~~~~~~~~~~~~~~~~~")
print("            \\")
print("             \\")
print("          (\\_/)")
print("          ( 👀)   ") 
print("         / >🍗  ")
print()
print("      HAPPY THANKSGIVING! ")
print()
print("     To those who celebrate,")
print("     may your day be filled with")
print("     warmth, gratitude, and good food!")
print()
print("     To everyone else,")
print("     wishing you a wonderful day")
print("     wherever you are!")
print()
print("=|" * 30)
